# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  vmManagerImage: 'azure-vm-manager:$(build.buildId)'
  repoName: neilswinton

steps:
- task: Docker@1
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: "Dockerhub(neilswinton)"
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: azure-vm-manager/Dockerfile
    imageName: $(Build.Repository.Name)/azure-vm-manager
- script: docker image ls && echo $(Build.Repository.Name) && echo $(repoName)
  displayName: 'docker image ls'
